//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatHang
    {
        public int ID { get; set; }
        public string TenNguoiDat { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public string MailZalo { get; set; }
        public string TenHang { get; set; }
        public System.DateTime ThoiGianCanLay { get; set; }
        public int SoLuong { get; set; }
        public string MoTa { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> CreateDt { get; set; }
    }
}
