//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhapHang
    {
        public int ID { get; set; }
        public System.DateTime NgayNhapHang { get; set; }
        public int ID_Product { get; set; }
        public int SoLuong { get; set; }
        public string TinhTrang { get; set; }
        public string Hang { get; set; }
        public string PhanLoaiXe { get; set; }
        public string MoTa { get; set; }
        public string Loai { get; set; }
    }
}
