//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinSanPham
    {
        public int ID { get; set; }
        public string Hieu { get; set; }
        public string Doi { get; set; }
        public string Hang { get; set; }
        public string MoTa { get; set; }
        public string TinhTrang { get; set; }
        public string PhanLoai { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
        public string Image5 { get; set; }
    }
}
